src/components/Blocks/BlockCard.vue, tests/unit/Blocks/BlockCard.spec.js
=> Fix blok starttijd

src/components/Navigation/ViewNavigationBar.vue, src/components/Navigation/activeTab.js, src/components/Regatta/RegattaOverview.vue, tests/unit/navigation/activeTab.spec.js, tests/unit/services/Regatta.spec.js, tests/unit/services/Service.spec.js
=> Improve deeplinking

src/components/Crews/SearchOverview.vue, src/views/IframeCrewDrawView.vue, src/views/IframeCrewResultsView.vue, src/views/IframeCrewSearchView.vue, src/views/IframeView.vue, src/views/analytics.js
fixes small finishtime
on mobile remove blade and add field
sort crews by backnumber
=> enhance cluboverview

src/App.vue, src/components/Navigation/MobileNavBar.vue, src/components/Navigation/NavBar.vue, src/components/Navigation/navigation.js, tests/unit/navigation/navigation.spec.js
=> highlight links on the navbar

src/components/Events/EventsOverview.vue
=> separate mix events from other events

src/components/Navigation/MobileNavBar.vue, src/components/Navigation/NavBar.vue, src/components/Navigation/navigation.js, tests/unit/navigation/navigation.spec.js
when switching from draw to results keep current settings like match, year and field on mobile
=> keep current settings when switching type on mobile

src/services/Regatta.js, tests/unit/services/Regatta.spec.js
=> sort events based on starting order

src/components/Team/TeamPopup.vue, tests/unit/Team/TeamPopup.spec.js
add crew comments and subfield as attributes of the team popup #45
=> fix attributes in the team popup

src/components/Blocks/BlockCard.vue, src/components/Blocks/BlockOverview.vue, src/components/Events/EventsOverview.vue, src/services/Regatta.js, tests/unit/Blocks/BlockCard.spec.js, tests/unit/services/Regatta.spec.js
fixes issue #38
this is done on the frontend and not the backend
=> fix block sorting on the frontend #38

src/components/Blocks/BlockCard.vue, src/components/Blocks/BlockOverview.vue, src/components/Events/EventsOverview.vue, src/components/Navigation/MobileNavBar.vue, src/components/Navigation/NavBar.vue, src/components/Navigation/SwitchElement.vue, src/components/Time/FinishTime.vue, tests/unit/navigation/SwitchElement.spec.js
=> Fix some styling issues and fix the strong of uitslagen and loting

src/components/Blocks/BlockCard.vue, src/components/Crews/SearchOverview.vue, src/components/Events/EventsTable.vue, src/helpers/Routing.js, src/router.js, tests/unit/helpers/Routing.spec.js
=> Implemented field links from clubs and search. Improved routing.

src/components/Crews/ResultOverview.vue, src/components/Crews/findClockingLocations.js, src/components/Time/Time.js, src/helpers/uniqBy.js, tests/unit/Crews/ResultOverview.spec.js, tests/unit/Crews/findClockingLocation.spec.js, tests/unit/Time/Time.spec.js, tests/unit/helpers/uniqBy.spec.js
=> Tussentijden 

Jenkinsfile
added the tests here, might be overkill since apperently they also run in travis.
=> Rewrite jenkins file

src/Views/CrewDrawView.vue, src/Views/CrewResultsView.vue, src/Views/CrewSearchView.vue, src/Views/RegattaView.vue, src/router.js, tests/unit/Views/RegattaView.spec.js
Iframe and main site should share as much as possible I think. Setup basic routing
=> Rename files to allow reuse of compoments

src/Views/VenuesOverview.vue, src/components/Navigation/SwitchRegatta.vue, src/router.js
This might need some more styling, but functionality is there
=> Venues page

src/components/Blocks/BlockCard.vue, src/components/Navigation/NavBar.vue, src/components/Navigation/SwitchRegatta.vue
Should make regatta selectio nscrollable
=> Scrollable selection

src/Helpers/Routing.js, src/Views/VenuesOverview.vue, src/components/Navigation/FrontpageNavBar.vue, src/components/Navigation/NavBar.vue, src/components/Regatta/RegattaOverview.vue, tests/unit/Helpers/Routing.spec.js
Adds:
A special navbar for venues overview
A home redirect on the 'hoesnelwasik' text and the iris logo.
=> Frontpage navbar

src/components/Crews/ResultOverview.vue, src/components/Crews/findMultipleRounds.js, src/components/Time/Time.js, tests/unit/Crews/findMultipleRounds.js.spec.js, tests/unit/Time/Time.spec.js
Ik heb nu de ronde tijden kunnen weergeven. Ook nog een beetje robust gemaakt door te checken of er wel gestart is. Het voelt een beetje beun maar ik zou niet weten hoe het netter kan. 
Enige wat nog moet is dat als er een meerkamp is dat de Finish Time de computed time wordt ipv de uitslag van de 1e ronde. Enig idee hoe dat te doen?
=> show results for rounds

src/components/Crews/ResultOverview.vue, src/components/Crews/findMultipleRounds.js, tests/unit/Crews/ResultOverview.spec.js
Closes #259 
Now correctly show only 1 finish time in a simple race.
Also added a small test for the All around matches.
=> Fix multiple finish times

src/components/Time/FinalTime.vue, tests/unit/Crews/ResultOverview.spec.js
=> Remove time when DNS, DNF etc.

src/components/Crews/findMultipleRounds.js, src/router.js, tests/unit/Crews/findMultipleRounds.js.spec.js
This will should fix the following error which occurred during TBR.
TypeError: t.times[0] is undefined
e findMultipleRounds.js:8
e findMultipleRounds.js:8
Ir findMultipleRounds.js:5
fields ResultOverview.vue:147
=> check and test for no times error

src/components/Crews/findMultipleRounds.js, tests/unit/Crews/findMultipleRounds.js.spec.js
These additional test model different scenario's which could go wrong. It should also include the current crash that sometimes happens.
=> Additional tests for when times is empty and when times.times is empty

src/components/Crews/findMultipleRounds.js, src/router.js, tests/unit/Crews/findMultipleRounds.js.spec.js
=> times undefined more thourough fix
